services:
  playnirvana:
    build:
      context: .
    depends_on:
      sqlserver:
        condition: service_started
    container_name: playnirvana
    environment:
      - ConnectionStrings__PlayNirvanaConnectionString=Server=sqlserver;Database=PlayNirvana;User Id=sa;Password=Welcome$2u;Encrypt=False
      - ASPNETCORE_ENVIRONMENT=Development
    command: >
      bash -c "echo 'Running migrations...' &&
             ./ticketModuleMigrations.exe &&
             ./roundModuleMigrations.exe
             echo 'Migrations complete. Starting application...' &&
             dotnet PlayNirvana.Web.dll"
    ports:
      - 8080:8080
    
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Welcome$2u"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql

volumes:
  sqlserverdata: