// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlayNirvana.TicketModule.Infrastructure.DataContext;

#nullable disable

namespace PlayNirvana.TicketModule.Infrastructure.DataContext.Migrations
{
    [DbContext(typeof(TicketModuleDbContext))]
    [Migration("20250830100042_AddChangeTrackingColumnsToBet")]
    partial class AddChangeTrackingColumnsToBet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tickets")
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PlayNirvana.CommonModule.SharedEntites.RaceDogResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Place")
                        .HasColumnType("int");

                    b.Property<int>("RacingDogId")
                        .HasColumnType("int");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RaceDogResults", "rounds", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("PlayNirvana.TicketModule.Domain.Entites.Bet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BetStatus")
                        .HasColumnType("int");

                    b.Property<int>("BetType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("Bets", "tickets");
                });

            modelBuilder.Entity("PlayNirvana.TicketModule.Domain.Entites.DogPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BetId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("RacingDogId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BetId");

                    b.ToTable("DogPositions", "tickets");
                });

            modelBuilder.Entity("PlayNirvana.TicketModule.Domain.Entites.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("BetAmount")
                        .HasColumnType("float");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PaymentReservationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TicketStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.Property<double>("WinAmount")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Tickets", "tickets");
                });

            modelBuilder.Entity("PlayNirvana.TicketModule.Domain.Entites.Bet", b =>
                {
                    b.HasOne("PlayNirvana.TicketModule.Domain.Entites.Ticket", null)
                        .WithMany("Bets")
                        .HasForeignKey("TicketId");
                });

            modelBuilder.Entity("PlayNirvana.TicketModule.Domain.Entites.DogPosition", b =>
                {
                    b.HasOne("PlayNirvana.TicketModule.Domain.Entites.Bet", null)
                        .WithMany("DogPositions")
                        .HasForeignKey("BetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PlayNirvana.TicketModule.Domain.Entites.Bet", b =>
                {
                    b.Navigation("DogPositions");
                });

            modelBuilder.Entity("PlayNirvana.TicketModule.Domain.Entites.Ticket", b =>
                {
                    b.Navigation("Bets");
                });
#pragma warning restore 612, 618
        }
    }
}
